[azure]
account_name = "testeblob1"
account_key = "K8MN/d7yf9yxRvrV4Pg+KJTXh9f0bmbnHSdeIXGd4ucTgeC79ZgivZqEOiqb2qHwseZUqDnq9Lp7+ASt43B9VA=="
connection_string = "DefaultEndpointsProtocol=https;AccountName=testeblob1;AccountKey=K8MN/d7yf9yxRvrV4Pg+KJTXh9f0bmbnHSdeIXGd4ucTgeC79ZgivZqEOiqb2qHwseZUqDnq9Lp7+ASt43B9VA==;EndpointSuffix=core.windows.net"